"""instance backup report

Revision ID: 31250984815e
Revises: 366347991084
Create Date: 2026-10-06 19:52:40.127753
"""

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "31250984815e"
down_revision = "366347991084"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "instance_backup_report",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("commcell_id", sa.Integer(), nullable=False),
        sa.Column("instance_id", sa.Uuid(), nullable=False),
        sa.Column("client", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("instance", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("app_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("job_id", sa.BigInteger(), nullable=False),
        sa.Column("job_status", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("job_ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("discovered", sa.Integer(), nullable=False),
        sa.Column("backed_up", sa.Integer(), nullable=False),
        sa.Column("reported_backed_up", sa.Integer(), nullable=True),
        sa.Column("reported_skipped", sa.Integer(), nullable=True),
        sa.Column("missed", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("unconfirmed", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["commcell_id"],
            ["commcell.id"],
        ),
        sa.ForeignKeyConstraint(
            ["instance_id"],
            ["source_object.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "commcell_id", "instance_id", "job_id", name="uq_instance_backup_report"
        ),
    )
    op.create_index(
        op.f("ix_instance_backup_report_instance_id"),
        "instance_backup_report",
        ["instance_id"],
        unique=False,
    )
    op.add_column("source_object", sa.Column("last_full_job_id", sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("source_object", "last_full_job_id")
    op.drop_index(
        op.f("ix_instance_backup_report_instance_id"), table_name="instance_backup_report"
    )
    op.drop_table("instance_backup_report")
    # ### end Alembic commands ###
