"""source objects

Revision ID: 366347991084
Revises: fcaf1fd992b1
Create Date: 2026-10-06 19:37:44.939974
"""

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "366347991084"
down_revision = "fcaf1fd992b1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "source_object",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("commcell_id", sa.Integer(), nullable=False),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("app_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("last_backup_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_backup_job_id", sa.BigInteger(), nullable=True),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("present", sa.Boolean(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_run_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["commcell_id"],
            ["commcell.id"],
        ),
        sa.ForeignKeyConstraint(
            ["last_seen_run_id"],
            ["collection_run.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["source_object.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("commcell_id", "kind", "source_key", name="uq_source_object_key"),
    )
    op.create_index(
        "ix_source_object_kind_present",
        "source_object",
        ["commcell_id", "kind", "present"],
        unique=False,
    )
    op.create_index(op.f("ix_source_object_name"), "source_object", ["name"], unique=False)
    op.create_index(
        op.f("ix_source_object_parent_id"), "source_object", ["parent_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_source_object_parent_id"), table_name="source_object")
    op.drop_index(op.f("ix_source_object_name"), table_name="source_object")
    op.drop_index("ix_source_object_kind_present", table_name="source_object")
    op.drop_table("source_object")
    # ### end Alembic commands ###
