"""initial schema

Revision ID: 5ee960797e83
Revises:
Create Date: 2026-10-04 20:54:40.257978
"""

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "5ee960797e83"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "commcell",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_commcell_name"), "commcell", ["name"], unique=True)
    op.create_table(
        "collection_run",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("commcell_id", sa.Integer(), nullable=False),
        sa.Column("mode", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lookup_seconds", sa.BigInteger(), nullable=False),
        sa.Column("jobs_collected", sa.Integer(), nullable=False),
        sa.Column("jobs_reconciled", sa.Integer(), nullable=False),
        sa.Column("jobs_missing", sa.Integer(), nullable=False),
        sa.Column("error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["commcell_id"],
            ["commcell.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_run_commcell_status_started",
        "collection_run",
        ["commcell_id", "status", "started_at"],
        unique=False,
    )
    op.create_table(
        "job",
        sa.Column("commcell_id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("state", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("job_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("operation", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("backup_level", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("app_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("client_id", sa.Integer(), nullable=True),
        sa.Column("client_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("subclient_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("backupset_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("instance_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("storage_policy", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("percent_complete", sa.Float(), nullable=True),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_update_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("elapsed_seconds", sa.BigInteger(), nullable=True),
        sa.Column("size_of_application", sa.BigInteger(), nullable=True),
        sa.Column("size_of_media", sa.BigInteger(), nullable=True),
        sa.Column("total_files", sa.BigInteger(), nullable=True),
        sa.Column("failed_files", sa.BigInteger(), nullable=True),
        sa.Column("pending_reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_aged", sa.Boolean(), nullable=True),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_run_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["commcell_id"],
            ["commcell.id"],
        ),
        sa.ForeignKeyConstraint(
            ["last_seen_run_id"],
            ["collection_run.id"],
        ),
        sa.PrimaryKeyConstraint("commcell_id", "job_id"),
    )
    op.create_index(op.f("ix_job_client_name"), "job", ["client_name"], unique=False)
    op.create_index("ix_job_commcell_active", "job", ["commcell_id", "is_active"], unique=False)
    op.create_index("ix_job_commcell_start", "job", ["commcell_id", "start_time"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_job_commcell_start", table_name="job")
    op.drop_index("ix_job_commcell_active", table_name="job")
    op.drop_index(op.f("ix_job_client_name"), table_name="job")
    op.drop_table("job")
    op.drop_index("ix_run_commcell_status_started", table_name="collection_run")
    op.drop_table("collection_run")
    op.drop_index(op.f("ix_commcell_name"), table_name="commcell")
    op.drop_table("commcell")
    # ### end Alembic commands ###
