"""backfill position

Revision ID: fcaf1fd992b1
Revises: 5ee960797e83
Create Date: 2026-10-06 09:31:47.745524
"""

import sqlalchemy as sa
from alembic import op

revision = "fcaf1fd992b1"
down_revision = "5ee960797e83"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("commcell", sa.Column("backfilled_to", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "commcell",
        sa.Column("backfill_complete", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("commcell", "backfill_complete")
    op.drop_column("commcell", "backfilled_to")
    # ### end Alembic commands ###
